name: The Truth About Apple
favicon: null
layout_spectrum: 0.5122950696386397
typography_spectrum: 0.19298700289800763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4281030651181936
  lightness: 0.7358230021782219
  saturation: 0.5631763469427824
  rhythmicContrast: 0.03590604057535529
purpose: []
